version: "3.3"

networks:
   default:

services:
  master_authority:
    container_name: master_ra
    build:
      context: ../master_authority
      dockerfile: ../master_authority/MA.Dockerfile
    restart: always
    ports:
      - 5000:5000

  registration_authority:
    container_name: registration_ra
    build:
      context: ../registration_authority
      dockerfile: ../registration_authority/RA.Dockerfile
    restart: always
    ports:
      - 5001:5000

  verifier:
    container_name: verifier
    build:
      context: ../verifier/
      dockerfile: ../verifier/Verifier.Dockerfile
    restart: always
    ports:
      - 5002:5000

  redis:
    container_name: verifier_db
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ../redis/cache:/data
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: persistence
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=cloud_storage
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ../mongodb/mongo-volume:/data/db
      - ../mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports:
      - '27017-27019:27017-27019'